/*
 * SmallRemoteCommands.h
 *
 * Created: 2020-12-09 6:52:07 PM
 *  Author: charl
 */ 


#ifndef SMALLREMOTECOMMANDS_H_
#define SMALLREMOTECOMMANDS_H_

#define SMALLREMOTE_BRIGHTNESSUP	0xFF
#define SMALLREMOTE_BRIGHTNESSDOWN	0x7F
#define SMALLREMOTE_OFF				0xBF
#define SMALLREMOTE_ON				0x3F
#define SMALLREMOTE_RED				0xDF
#define SMALLREMOTE_GREEN			0x5F
#define SMALLREMOTE_BLUE			0x9F
#define SMALLREMOTE_WHITE			0x1F
#define SMALLREMOTE_REDORANGE		0xEF
#define SMALLREMOTE_LIGHTGREEN		0x6F
#define SMALLREMOTE_ROYALBLUE		0xAF
#define SMALLREMOTE_FLASH			0x2F
#define SMALLREMOTE_ORANGE			0xCF
#define SMALLREMOTE_CYAN			0x4F
#define SMALLREMOTE_DEEPPURPLE		0x8F
#define SMALLREMOTE_STROBE			0x0F
#define SMALLREMOTE_LIGHTORANGE		0xF7
#define SMALLREMOTE_TEAL			0x77
#define SMALLREMOTE_PURPLE			0xB7
#define SMALLREMOTE_FADE			0x37
#define SMALLREMOTE_YELLOW			0xD7
#define SMALLREMOTE_DEEPBLUE		0x57
#define SMALLREMOTE_PINK			0x97
#define SMALLREMOTE_SMOOTH			0x17

#endif /* SMALLREMOTECOMMANDS_H_ */